### ISSUE TITLE
License in LICENSE file is GPL

### ISSUE THREAD

**Issue by klugier** [ismail-yilmaz/Bobcat#1]
In README.md there is information about the license and it is BSD. However, in license file you have GNU GPL.

**Comment by ismail-yilmaz** [comment]
> In README.md there is information about the license and it is BSD. However, in license file you have GNU GPL.

Hello Kluiger,

Bobcat has a  GPL-3 license. It is stated bot in Bobcat/About/Licenses section and README. In readme, a shorthand version of GPL-3 notice is used. I couldn't find any references to BSD? Could you point me to it, so that  I can change it?

**Comment by klugier** [comment]
My bad, it looks like in README.md there is explicit information about GPL.
